export const CONTENT_TYPES = [
  { id:'hooks', icon:'🔥', label:'Hooks', desc:'10 scroll-stoppers' },
  { id:'post', icon:'📱', label:'Social Posts', desc:'7 platform-native concepts' },
  { id:'caption', icon:'📝', label:'Captions', desc:'3 captions + hashtags' },
  { id:'carousel', icon:'🎠', label:'Carousels', desc:'5 slides + AI images' },
  { id:'reel', icon:'🎥', label:'Reel Scripts', desc:'Timed beats, VO + visuals' },
  { id:'video', icon:'🎬', label:'Video Scripts', desc:'60–90s YouTube/ads' },
  { id:'blog', icon:'✍️', label:'Blog Articles', desc:'SEO-structured outline + intro' },
  { id:'email', icon:'📧', label:'Email Campaigns', desc:'3-email sequence' },
  { id:'linkedin', icon:'💼', label:'LinkedIn Articles', desc:'Thought-leadership post' },
  { id:'product', icon:'🛍️', label:'Product Descriptions', desc:'E-commerce ready' },
  { id:'press', icon:'📰', label:'Press Releases', desc:'Newsroom format' },
  { id:'adcopy', icon:'🎯', label:'Ad Copy', desc:'Meta/Google variants' },
  { id:'landing', icon:'🛬', label:'Landing Page Copy', desc:'Hero → CTA sections' },
  { id:'podcast', icon:'🎙️', label:'Podcast Scripts', desc:'Intro, segments, outro' },
  { id:'newsletter', icon:'🗞️', label:'Newsletters', desc:'Issue structure + copy' },
  { id:'seo', icon:'🔎', label:'SEO Content', desc:'Keywords, meta, headings' },
];
