export const CONTENT_TYPES = [
  { id:'hooks', icon:'🔥', msym:'local_fire_department', label:'Hooks', desc:'10 scroll-stoppers' },
  { id:'post', icon:'📱', msym:'dynamic_feed', label:'Social Posts', desc:'7 platform-native concepts' },
  { id:'caption', icon:'📝', msym:'chat_bubble', label:'Captions', desc:'3 captions + hashtags' },
  { id:'carousel', icon:'🎠', msym:'view_carousel', label:'Carousels', desc:'5 slides + AI images' },
  { id:'reel', icon:'🎥', msym:'movie', label:'Reel Scripts', desc:'Timed beats, VO + visuals' },
  { id:'video', icon:'🎬', msym:'videocam', label:'Video Scripts', desc:'60–90s YouTube/ads' },
  { id:'blog', icon:'✍️', msym:'article', label:'Blog Articles', desc:'SEO-structured outline + intro' },
  { id:'email', icon:'📧', msym:'mail', label:'Email Campaigns', desc:'3-email sequence' },
  { id:'linkedin', icon:'💼', msym:'work', label:'LinkedIn Articles', desc:'Thought-leadership post' },
  { id:'product', icon:'🛍️', msym:'shopping_bag', label:'Product Descriptions', desc:'E-commerce ready' },
  { id:'press', icon:'📰', msym:'newspaper', label:'Press Releases', desc:'Newsroom format' },
  { id:'adcopy', icon:'🎯', msym:'ads_click', label:'Ad Copy', desc:'Meta/Google variants' },
  { id:'landing', icon:'🛬', msym:'web', label:'Landing Page Copy', desc:'Hero → CTA sections' },
  { id:'podcast', icon:'🎙️', msym:'mic', label:'Podcast Scripts', desc:'Intro, segments, outro' },
  { id:'newsletter', icon:'🗞️', msym:'subscriptions', label:'Newsletters', desc:'Issue structure + copy' },
  { id:'seo', icon:'🔎', msym:'search', label:'SEO Content', desc:'Keywords, meta, headings' },
];
